name: Golang
on:
  push:
    branches: [main]
  pull_request: {}
  workflow_dispatch: {}
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
      - name: Test
        run: |-
          GOLANG_TEST_FLAGS="-v -json -timeout 2m" make test
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    needs: test
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Dependencies
        run: go mod download
      - name: Build
        run: make build
  formatting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Check Formatting
        run: |-
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "Files are not properly formatted"
            gofmt -s -l .
            exit 1
          fi
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    needs: test
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Dependencies
        run: go mod download
      - name: Run Coverage
        run: make tmp/coverage.out
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: src/tmp/coverage.out
